#!/bin/bash -i
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Author: Bryant Treacle
# Date Created: 2018-12-07
# Date last modified: 2018-12-07
# Purpose: This script will replace the so-user-passwd script in Security Onion to enforce DoD compliant password policies.

###########################
#  elevated access check  #
###########################

if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "This script must be run as root."
    exit
fi 
#######################
#  User Name function #
#######################
dod_user_name()
{
echo ""
echo "Enter the username that you'd like to change the password for."
read -p "Username: " USER_NAME
dod_user_pass
}
################################
#  DoD user password function  #
################################
dod_user_pass()
{
echo "Please enter a password following DoD guidance."
read -s -p "User Password: " USER_PASS
#Check if the password Length is greater or equal to 15 characters
if [[ ${USER_PASS} -ge 15 ]]; then
    # Check if the password has at least 2 upper case letters
    if [[ "$USER_PASS" =~ (.*[A-Z].*){2} ]]; then
        # Check if the password has at least 2 digits
        if [[ "$USER_PASS" =~ (.*[0-9].*){2} ]]; then
            # Check if the password has at least 2 special characters
            if [[ "$USER_PASS" =~ (.*[!\@#\$%^\&*()_+].*){2} ]]; then
                dod_user_pass_verify
            else
                echo "Please use at least 2 of the following special characters !@#$%^&*()_+ "
                dod_user_pass
            fi
        else
            echo "Your password must include 2 numbers."
            dod_user_pass
        fi
    else
        echo "Your password must include 2 upper case characters."
        dod_user_pass
    fi
else
    echo "Your password must be at least 15 characters in length."
    dod_user_pass
fi
}

#############################################
#  DoD user password verification function  #
#############################################
dod_user_pass_verify()
{
echo ""
echo "Please verify password."
read -s -p "verify: " USER_PASS_VERIFY
echo ""
dod_pass_compare
}

################################
#  Compare Passwords Function  #
################################
# Check passwords to see if they are the same.
dod_pass_compare()
{
if [ "$USER_PASS" == "$USER_PASS_VERIFY" ]; then 
    user_passwd_sguild
else 
    echo ""
    echo "Your passwords do not match."
    dod_user_pass
fi
}

#################################
#  Add user to sguild function  #
#################################
user_passwd_sguild()
{
/usr/sbin/sguild-changepasswd "${USER_NAME}" "${USER_PASS}" >/dev/null 2>&1
if [ "${?}" -ne 0 ]
then
        echo "password could not be changed!"
else
        echo "Password for ${USER_NAME} successfully changed."
fi

exit 0
}

#########################
#  Magic happens below  #
#########################
dod_user_name

